apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-be
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-be
  template:
    metadata:
      labels:
        app: ecommerce-be
    spec:
      containers:
        - name: be
          image: registry.codebyluke.io.vn/ecommerce-badminton/ecommerce-be:18
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service;Database=ECommerceBadmintonDB;User Id=SA;Password=!65L8XQSakVq*q;TrustServerCertificate=true"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-be-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce-be
  ports:
    - protocol: TCP
      port: 80 # Port nội bộ trong cluster
      targetPort: 8080 # Port thực tế của app .NET
      nodePort: 30002 # Truy cập ngoài qua: <NodeIP>:30002
