apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-fe
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-fe
  template:
    metadata:
      labels:
        app: ecommerce-fe
    spec:
      containers:
        - name: fe
          image: registry.codebyluke.io.vn/ecommerce-badminton/ecommerce-fe:19
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NEXT_PUBLIC_API_BASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-fe-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce-fe
  ports:
    - protocol: TCP
      port: 80 # Port nội bộ của Service
      targetPort: 3000 # Port mà ứng dụng trong Pod đang chạy
      nodePort: 30001 # Port để truy cập từ ngoài (30000-32767)
