apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-be
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-be
  template:
    metadata:
      labels:
        app: ecommerce-be
    spec:
      containers:
        - name: be
          # Image này sẽ do Jenkins build và push
          image: harbor.local:30080/my-apps/ecommerce-be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: ASPNETCORE_ENVIRONMENT
            # Quan trọng: K8s ghép chuỗi kết nối động
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service;Database=ECommerceBadmintonDB;User Id=SA;Password=!65L8XQSakVq*q;TrustServerCertificate=true"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-be-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: ecommerce-be
  ports:
    - port: 80
      targetPort: 8080
